# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.5-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: expense_tracker
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: expense_tracker
          POSTGRES_PASSWORD: root123

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - expense_tracker-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - expense_tracker-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: expense_tracker-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rake test
          when: always

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results